@echo off
@echo "Removing bin release files"
powershell -Command "If (Test-Path 'bin\release\*') { Remove-Item 'bin\release\*' -Recurse -Force }"
@echo "Removing bin debug files"
powershell -Command "If (Test-Path 'bin\debug\*') { Remove-Item 'bin\debug\*' -Recurse -Force }"
@echo "Removing build release files"
powershell -Command "If (Test-Path 'build\release\*') { Remove-Item 'build\release\*' -Recurse -Force }"
@echo "Removing build debug files"
powershell -Command "If (Test-Path 'build\debug\*') { Remove-Item 'build\debug\*' -Recurse -Force }"
@echo "Removing out files"
powershell -Command "If (Test-Path 'out\*') { Remove-Item 'out\*' -Recurse -Force }"
@echo "Done"
