/*******************************************************************************
 * Copyright (C) 2018 Charly Lamothe                                           *
 *                                                                             *
 * This file is part of LibUnknownEchoUtilsModule.                             *
 *                                                                             *
 *   Licensed under the Apache License, Version 2.0 (the "License");           *
 *   you may not use this file except in compliance with the License.          *
 *   You may obtain a copy of the License at                                   *
 *                                                                             *
 *   http://www.apache.org/licenses/LICENSE-2.0                                *
 *                                                                             *
 *   Unless required by applicable law or agreed to in writing, software       *
 *   distributed under the License is distributed on an "AS IS" BASIS,         *
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *
 *   See the License for the specific language governing permissions and       *
 *   limitations under the License.                                            *
 *******************************************************************************/

#ifndef UNKNOWNECHOUTILSMODULE_COLOR_H
#define UNKNOWNECHOUTILSMODULE_COLOR_H

#define UNKNOWNECHOUTILSMODULE_COLOR_ID_ATTRIBUTE_RESET     0
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_ATTRIBUTE_BOLD      1
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_ATTRIBUTE_DIM       2
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_ATTRIBUTE_UNDERLINE 4
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_ATTRIBUTE_REVERSE   7
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_ATTRIBUTE_HIDDEN    8

#define UNKNOWNECHOUTILSMODULE_COLOR_ID_FOREGROUND_BLACK   30
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_FOREGROUND_RED     31
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_FOREGROUND_GREEN   32
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_FOREGROUND_YELLOW  33
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_FOREGROUND_BLUE    34
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_FOREGROUND_MAGENTA 35
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_FOREGROUND_CYNAN   36
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_FOREGROUND_WHITE   37

#define UNKNOWNECHOUTILSMODULE_COLOR_ID_BACKGROUND_BLACK   40
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_BACKGROUND_RED     41
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_BACKGROUND_GREEN   42
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_BACKGROUND_YELLOW  43
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_BACKGROUND_BLUE    44
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_BACKGROUND_MAGENTA 45
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_BACKGROUND_CYNAN   46
#define UNKNOWNECHOUTILSMODULE_COLOR_ID_BACKGROUND_WHITE   47

#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET "\x1B[0m"

#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_BLACK   "\x1B[30m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_RED     "\x1B[31m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_GREEN   "\x1B[32m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_YELLOW  "\x1B[33m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_BLUE    "\x1B[34m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_MAGENTA "\x1B[35m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_CYNAN   "\x1B[36m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_WHITE   "\x1B[37m"

#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_BLACK   "\x1B[40m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_RED     "\x1B[41m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_GREEN   "\x1B[42m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_YELLOW  "\x1B[43m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_BLUE    "\x1B[44m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_MAGENTA "\x1B[45m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_CYNAN   "\x1B[46m"
#define UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_WHITE   "\x1B[47m"

#define UNKNOWNECHOUTILSMODULE_COLORIZE_FOREGROUND_RED(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_RED x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_FOREGROUND_GREEN(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_GREEN x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_FOREGROUND_YELLOW(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_YELLOW x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_FOREGROUND_BLUE(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_BLUE x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_FOREGROUND_MAGENTA(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_MAGENTA x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_FOREGROUND_CYAN(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_CYAN x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_FOREGROUND_WHITE(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_FOREGROUND_WHITE x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET

#define UNKNOWNECHOUTILSMODULE_COLORIZE_BACKGROUND_RED(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_RED x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_BACKGROUND_GREEN(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_GREEN x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_BACKGROUND_YELLOW(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_YELLOW x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_BACKGROUND_BLUE(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_BLUE x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_BACKGROUND_MAGENTA(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_MAGENTA x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_BACKGROUND_CYAN(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_CYAN x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_BACKGROUND_WHITE(x) UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_BACKGROUND_WHITE x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET

#define UNKNOWNECHOUTILSMODULE_COLORIZE(x, color) color x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET

#define UNKNOWNECHOUTILSMODULE_COLORIZE_BOLD(x) "\x1B[1m" x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_DIM(x) "\x1B[2m" x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_UNDERLINE(x) "\x1B[4m" x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_REVERSE(x) "\x1B[7m" x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET
#define UNKNOWNECHOUTILSMODULE_COLORIZE_HIDDEN(x) "\x1B[8m" x UNKNOWNECHOUTILSMODULE_COLOR_ESCAPE_RESET

char *ueum_colorize_string(const char *string, int attribute_id, int foreground_id, int background_id);

#endif
